title: Meisam Ashraf
description: Industrial AI Research Scientist – Time-Series & Generative Modeling for Medical Devices
theme: minima
markdown: kramdown

author:
  name: Meisam Ashraf
  email: meisash@gmail.com

header_pages: []